//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P507Pr0ject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleMedicine
    {
        public int Id { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public int Amount { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
